### ISSUE TITLE
ps4000 wrapper is missing many API calls

### ISSUE THREAD

**Issue by pigrew** [picotech/picosdk-c-sharp-examples#3]
The C# wrappers are missing many of the C API calls. I've noticed this in the ps4000 wrapper library.

I've gone through and added the calls I need to use for my project, but it seemed an awfully inefficient process. Is there some automated way that the wrappers can be generated (Like creating an XML API definition file, which can be used to generate the wrappers in various languages)?

If not, I'll put together a pull request to update the C# library.

**Comment by hsmistry** [comment]
@pigrew, we currently add functions manually as required for examples. Automatic generation might be possible but there may be cases where the files would still have to be edited e.g. where a pointer to a short value but actually be an array.

Please submit a pull request on another branch and we'll review the proposed changes.

**Comment by pigrew** [comment]
Sounds good. I have a deadline in about two weeks, and I'll create the pull request then.

**Comment by hsmistry** [comment]
OK, that's fine.

**Comment by pigrew** [comment]
I'm waiting for a resolution of pull request #4 before submitting these changes. I don't know if #4 was caused my my system's misconfiguration or not.

**Comment by hsmistry** [comment]
@pigrew pull request #4 has been resolved.
