### ISSUE TITLE
TC08 short pointers?

### ISSUE THREAD

**Issue by InvisibleWaves** [picotech/picosdk-c-sharp-examples#5]
Just a quick question because I'm unsure of how the driver is implemented below the wrapper: the C# wrapper for the TC08 uses a short as a file handle, but wouldn't an IntPtr or SafeHandle be what a .NET developer would expect to see?

**Comment by hsmistry** [comment]
Hi @InvisibleWaves, thanks for your question. The driver uses a signed 16-bit integer for the handle parameter so we have used a short. Here is the definition from the C header file for the driver:

`PREF0 PREF1 int16_t PREF2 PREF3(usb_tc08_open_unit)
(
  void
);`

You could use short or Int16.

Hope this helps.
